# Generated by Django 4.1.3 on 2022-12-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
