# Generated by Django 4.1.3 on 2022-12-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_ordered_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered_times',
        ),
    ]
