# Generated by Django 4.1.3 on 2022-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_ordered_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='earnings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
