# Generated by Django 4.1.5 on 2023-01-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
